# Generated by Django 6.0.3 on 2026-04-07 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enseignants', '0001_initial'),
        ('etudiants', '0003_alter_etudiant_nationalite_alter_etudiant_passport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jury',
            fields=[
                ('idJury', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=150)),
                ('enseignants', models.ManyToManyField(related_name='jurys', to='enseignants.enseignant')),
            ],
        ),
        migrations.CreateModel(
            name='PFE',
            fields=[
                ('idPfe', models.AutoField(primary_key=True, serialize=False)),
                ('sujet', models.CharField(max_length=250)),
                ('duree', models.PositiveIntegerField(help_text='Durée en mois ou unité métier')),
                ('specialite', models.CharField(max_length=150)),
                ('encadrant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pfes_encadres', to='enseignants.enseignant')),
                ('jury', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pfes', to='pfes.jury')),
            ],
        ),
        migrations.CreateModel(
            name='PFEStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etudiant', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pfe_assignment', to='etudiants.etudiant')),
                ('pfe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='pfes.pfe')),
            ],
            options={
                'verbose_name': 'Affectation étudiant PFE',
                'verbose_name_plural': 'Affectations étudiants PFE',
            },
        ),
        migrations.AddField(
            model_name='pfe',
            name='etudiants',
            field=models.ManyToManyField(related_name='pfes', through='pfes.PFEStudent', to='etudiants.etudiant'),
        ),
    ]
