# Generated by Django 6.0.4 on 2026-04-16 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enseignants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diplome',
            name='specialite',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
