# Generated by Django 6.0.4 on 2026-04-19 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academique', '0003_alter_module_type'),
        ('enseignants', '0004_remove_enseignant_maxgroupespfe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enseignants', to='academique.departement'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='role',
            field=models.CharField(choices=[('enseignant', 'Enseignant'), ('chef_departement', 'Chef de Département'), ('admin', 'Administrateur')], default='enseignant', max_length=20),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
