# Generated by Django 6.0.4 on 2026-04-19 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enseignants', '0005_enseignant_departement_enseignant_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enseignant',
            name='departement',
        ),
        migrations.RemoveField(
            model_name='enseignant',
            name='role',
        ),
        migrations.RemoveField(
            model_name='enseignant',
            name='user',
        ),
    ]
