# Generated by Django 6.0.4 on 2026-04-16 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enseignants', '0002_alter_diplome_specialite'),
        ('etudiants', '0002_remove_etudiant_dateinscription_etudiant_nationalite_and_more'),
        ('pfes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rapporteur',
            fields=[
                ('matricule', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('cin', models.CharField(max_length=8, unique=True)),
                ('nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('numtel', models.CharField(max_length=20)),
                ('grade', models.CharField(max_length=50)),
                ('dateRecrutement', models.DateField()),
                ('statutAdministratif', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='pfe',
            name='jury',
        ),
        migrations.AddField(
            model_name='pfe',
            name='convention_file',
            field=models.FileField(blank=True, null=True, upload_to='conventions/'),
        ),
        migrations.AddField(
            model_name='pfe',
            name='date_affectation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pfe',
            name='lettre_affectation_file',
            field=models.FileField(blank=True, null=True, upload_to='lettres_affectation/'),
        ),
        migrations.CreateModel(
            name='Soutenance',
            fields=[
                ('idSoutenance', models.AutoField(primary_key=True, serialize=False)),
                ('date_soutenance', models.DateField()),
                ('duree', models.PositiveIntegerField(help_text='Durée en minutes')),
                ('salle', models.CharField(max_length=100)),
                ('encadrant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='soutenances_encadrees', to='enseignants.enseignant')),
                ('etudiants', models.ManyToManyField(related_name='soutenances', to='etudiants.etudiant')),
                ('pfe', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soutenance', to='pfes.pfe')),
                ('rapporteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='soutenances', to='pfes.rapporteur')),
            ],
            options={
                'ordering': ['-date_soutenance'],
            },
        ),
        migrations.DeleteModel(
            name='Jury',
        ),
    ]
