# Generated by Django 6.0.4 on 2026-04-19 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enseignants', '0005_enseignant_departement_enseignant_role_and_more'),
        ('pfes', '0005_soutenance_heure_soutenance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soutenance',
            options={'ordering': ['-date_soutenance', '-heure_soutenance']},
        ),
        migrations.AlterField(
            model_name='parametrespfe',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='soutenance',
            name='rapporteur',
            field=models.ForeignKey(help_text='Enseignant rapporteur (exclut contrat doctorant et contrat docteur).', on_delete=django.db.models.deletion.PROTECT, related_name='soutenances_comme_rapporteur', to='enseignants.enseignant'),
        ),
    ]
