# Generated by Django 6.0.4 on 2026-04-27 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enseignants', '0007_enseignant_departement_enseignant_role_and_more'),
        ('pfes', '0006_alter_soutenance_options_alter_parametrespfe_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pfe',
            name='encadrant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pfes_encadres', to='enseignants.enseignant'),
        ),
    ]
