# Generated by Django 6.0.4 on 2026-04-19 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academique', '0002_specialite_alter_module_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='type',
            field=models.CharField(choices=[('cours', 'Cours'), ('td', 'Travaux Dirigés'), ('tp', 'Travaux Pratiques'), ('Optionnel', 'Optionnel')], default='cours', max_length=20),
        ),
    ]
