# Generated by Django 6.0.4 on 2026-04-22 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academique', '0003_alter_module_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='matiere',
            field=models.CharField(blank=True, help_text='Matière associée au module', max_length=255, null=True),
        ),
    ]
