# Generated by Django 6.0.4 on 2026-04-22 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academique', '0004_module_matiere'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='coefficient_ue',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Coefficient (Total UE)', max_digits=5),
        ),
        migrations.AddField(
            model_name='module',
            name='credit_ue',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Crédits (Total UE)', max_digits=5),
        ),
        migrations.AddField(
            model_name='module',
            name='vh_ci',
            field=models.IntegerField(default=0, help_text='Volume horaire (CI)'),
        ),
        migrations.AddField(
            model_name='module',
            name='vh_td',
            field=models.IntegerField(default=0, help_text='Volume horaire (TD)'),
        ),
        migrations.AlterField(
            model_name='module',
            name='coefficient',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Coefficient (par élément)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='module',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Crédits (par élément)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='module',
            name='matiere',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Elément constitutif (ECUE)'),
        ),
        migrations.AlterField(
            model_name='module',
            name='nom',
            field=models.CharField(max_length=255, verbose_name="Unité d'Enseignement (UE)"),
        ),
        migrations.AlterField(
            model_name='module',
            name='volume_horaire',
            field=models.IntegerField(default=0, help_text='Volume en heures (Cours/C)'),
        ),
    ]
