# Generated by Django 6.0.4 on 2026-04-22 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academique', '0005_module_coefficient_ue_module_credit_ue_module_vh_ci_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='coefficient',
        ),
        migrations.RemoveField(
            model_name='module',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='module',
            name='matiere',
        ),
        migrations.RemoveField(
            model_name='module',
            name='vh_ci',
        ),
        migrations.RemoveField(
            model_name='module',
            name='vh_td',
        ),
        migrations.RemoveField(
            model_name='module',
            name='volume_horaire',
        ),
        migrations.AddField(
            model_name='module',
            name='matieres',
            field=models.JSONField(blank=True, default=list, help_text='Liste des matières (ECUEs) avec leurs volumes, crédits et coefficients'),
        ),
    ]
