# Generated by Django 6.0.4 on 2026-04-22 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academique', '0006_remove_module_coefficient_remove_module_credit_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='module',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='module',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
