# Generated by Django 6.0.4 on 2026-04-22 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academique', '0007_alter_module_unique_together_alter_module_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='type',
        ),
    ]
