# Generated by Django 5.2.12 on 2026-03-24 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Titre",
            fields=[
                ("idTitre", models.AutoField(primary_key=True, serialize=False)),
                ("dateDebutTitre", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Enseignant",
            fields=[
                (
                    "matricule",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("cin", models.CharField(max_length=8, unique=True)),
                ("nom", models.CharField(max_length=20)),
                ("prenom", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("numtel", models.CharField(max_length=20)),
                ("grade", models.CharField(max_length=50)),
                ("dateRecrutement", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Contractuel",
            fields=[
                (
                    "titre_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="enseignants.titre",
                    ),
                ),
                ("dureeContrat", models.IntegerField()),
                ("dateDebutContrat", models.DateField()),
                ("dateFinContrat", models.DateField()),
            ],
            bases=("enseignants.titre",),
        ),
        migrations.CreateModel(
            name="Permanent",
            fields=[
                (
                    "titre_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="enseignants.titre",
                    ),
                ),
                ("dateTitularisation", models.DateField()),
                ("statutAdministratif", models.CharField(max_length=100)),
            ],
            bases=("enseignants.titre",),
        ),
        migrations.CreateModel(
            name="Vacataire",
            fields=[
                (
                    "titre_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="enseignants.titre",
                    ),
                ),
                ("nbHeures", models.IntegerField()),
                ("tauxHoraire", models.FloatField()),
            ],
            bases=("enseignants.titre",),
        ),
        migrations.AddField(
            model_name="titre",
            name="enseignant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="titres",
                to="enseignants.enseignant",
            ),
        ),
        migrations.CreateModel(
            name="Diplome",
            fields=[
                ("idDiplome", models.AutoField(primary_key=True, serialize=False)),
                ("libelleDiplome", models.CharField(max_length=100)),
                ("specialite", models.CharField(max_length=100)),
                ("dateObtention", models.DateField()),
                (
                    "enseignant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diplomes",
                        to="enseignants.enseignant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContratDocteur",
            fields=[
                (
                    "contractuel",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="enseignants.contractuel",
                    ),
                ),
                ("primeRecherche", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="ContratDoctorant",
            fields=[
                (
                    "contractuel",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="enseignants.contractuel",
                    ),
                ),
                ("sujetThese", models.CharField(max_length=200)),
                ("universiteInscription", models.CharField(max_length=150)),
                ("anneeThese", models.IntegerField()),
            ],
        ),
    ]
