# Generated by Django 6.0.3 on 2026-04-06 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Titre',
            fields=[
                ('idTitre', models.AutoField(primary_key=True, serialize=False)),
                ('dateDebutTitre', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Diplome',
            fields=[
                ('idDiplome', models.AutoField(primary_key=True, serialize=False)),
                ('libelleDiplome', models.CharField(max_length=100)),
                ('specialite', models.CharField(max_length=100)),
                ('universite', models.CharField(blank=True, max_length=100, null=True)),
                ('dateObtention', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('matricule', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('cin', models.CharField(max_length=8, unique=True)),
                ('nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('numtel', models.CharField(max_length=20)),
                ('grade', models.CharField(max_length=50)),
                ('dateRecrutement', models.DateField()),
                ('statutAdministratif', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomGrade', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contractuel',
            fields=[
                ('titre_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='enseignants.titre')),
                ('dureeContrat', models.IntegerField()),
                ('dateDebutContrat', models.DateField()),
                ('dateFinContrat', models.DateField()),
            ],
            bases=('enseignants.titre',),
        ),
        migrations.CreateModel(
            name='Permanent',
            fields=[
                ('titre_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='enseignants.titre')),
                ('dateTitularisation', models.DateField()),
                ('anneeInscription', models.IntegerField(blank=True, null=True)),
            ],
            bases=('enseignants.titre',),
        ),
        migrations.CreateModel(
            name='Vacataire',
            fields=[
                ('titre_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='enseignants.titre')),
                ('nbHeures', models.IntegerField()),
                ('tauxHoraire', models.FloatField()),
            ],
            bases=('enseignants.titre',),
        ),
        migrations.AddField(
            model_name='titre',
            name='enseignant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titres', to='enseignants.enseignant'),
        ),
        migrations.CreateModel(
            name='ContratDocteur',
            fields=[
                ('contractuel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='enseignants.contractuel')),
                ('primeRecherche', models.FloatField()),
                ('numeroOrdre', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContratDoctorant',
            fields=[
                ('contractuel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='enseignants.contractuel')),
                ('sujetThese', models.CharField(max_length=200)),
                ('universiteInscription', models.CharField(max_length=150)),
                ('anneeInscription', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnseignantDiplome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateObtention', models.DateField()),
                ('idDiplome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enseignants.diplome')),
                ('matricule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enseignants.enseignant')),
            ],
            options={
                'unique_together': {('matricule', 'idDiplome')},
            },
        ),
        migrations.CreateModel(
            name='EnseignantGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateDebut', models.DateField()),
                ('dateFin', models.DateField(blank=True, null=True)),
                ('matricule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enseignants.enseignant')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enseignants.grade')),
            ],
            options={
                'unique_together': {('matricule', 'grade', 'dateDebut')},
            },
        ),
    ]
