# Generated by Django 5.2.12 on 2026-03-24 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Etudiant",
            fields=[
                ("idEtudiant", models.AutoField(primary_key=True, serialize=False)),
                ("cin", models.CharField(max_length=8, unique=True)),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("numTel", models.CharField(max_length=8)),
                ("dateNaissance", models.DateField()),
                ("adresse", models.CharField(max_length=100)),
                ("dateInscription", models.DateField()),
            ],
        ),
    ]
