# Generated by Django 6.0.3 on 2026-04-05 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='dateInscription',
        ),
        migrations.AddField(
            model_name='etudiant',
            name='nationalite',
            field=models.CharField(default='TN', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etudiant',
            name='passport',
            field=models.CharField(default='Tunisienne', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
