# Generated by Django 6.0.3 on 2026-04-05 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0002_remove_etudiant_dateinscription_etudiant_nationalite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='nationalite',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='passport',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
