# Generated by Django 6.0.3 on 2026-04-07

from django.db import migrations


def add_test_students(apps, schema_editor):
    Etudiant = apps.get_model('etudiants', 'Etudiant')
    
    test_students = [
        {
            'cin': '12345678',
            'nom': 'Ahmed',
            'prenom': 'Ali',
            'email': 'ahmed.ali@example.com',
            'numTel': '01234567',
            'nationalite': 'Algérienne',
            'passport': 'AA123456',
            'dateNaissance': '2002-05-15',
            'adresse': 'Alger, Algérie'
        },
        {
            'cin': '12345679',
            'nom': 'Benali',
            'prenom': 'Fatima',
            'email': 'benali.fatima@example.com',
            'numTel': '01234568',
            'nationalite': 'Algérienne',
            'passport': 'AB234567',
            'dateNaissance': '2003-07-20',
            'adresse': 'Oran, Algérie'
        },
        {
            'cin': '12345680',
            'nom': 'Kassem',
            'prenom': 'Sara',
            'email': 'kassem.sara@example.com',
            'numTel': '01234569',
            'nationalite': 'Algérienne',
            'passport': 'AC345678',
            'dateNaissance': '2002-12-10',
            'adresse': 'Constantine, Algérie'
        },
        {
            'cin': '12345681',
            'nom': 'Douceur',
            'prenom': 'Mohammed',
            'email': 'douceur.mohammed@example.com',
            'numTel': '01234570',
            'nationalite': 'Algérienne',
            'passport': 'AD456789',
            'dateNaissance': '2003-02-25',
            'adresse': 'Annaba, Algérie'
        },
        {
            'cin': '12345682',
            'nom': 'Elkhir',
            'prenom': 'Yasmine',
            'email': 'elkhir.yasmine@example.com',
            'numTel': '01234571',
            'nationalite': 'Algérienne',
            'passport': 'AE567890',
            'dateNaissance': '2002-08-30',
            'adresse': 'Tizi Ouzou, Algérie'
        },
    ]
    
    for student_data in test_students:
        Etudiant.objects.get_or_create(cin=student_data['cin'], defaults=student_data)


def remove_test_students(apps, schema_editor):
    Etudiant = apps.get_model('etudiants', 'Etudiant')
    Etudiant.objects.filter(idEtudiant__in=[1, 2, 3, 4, 5]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0003_alter_etudiant_nationalite_alter_etudiant_passport'),
    ]

    operations = [
        migrations.RunPython(add_test_students, remove_test_students),
    ]
