# Generated by Django 6.0.4 on 2026-04-16 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='dateInscription',
        ),
        migrations.AddField(
            model_name='etudiant',
            name='nationalite',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='passport',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
