# Generated by Django 6.0.4 on 2026-04-20 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0003_etudiant_licence_specialite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='numTel',
            field=models.CharField(max_length=20),
        ),
    ]
